In [14]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Que1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans:

Yes, there is a difference in the data type of variables list_ and array_list. The variable list_ contains strings, while the array_list contains a numpy array of strings. Here's the code to print the data types of both variables:

In [23]:
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'str'>
Data type of array_list: <U1


Que2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

Ans:

In [28]:
print("Data type of elements in list_:")
for item in list_:
    print(type(item))

print("\nData type of elements in array_list:")
for item in array_list:
    print(type(item))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Que3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans:

In [30]:
#Change data type of array_list elements and print
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for item in list_:
    print(f"Data type of element '{item}': {type(item)}")

# Print data type of each element in array_list
for item in array_list:
    print(f"Data type of element '{item}': {type(item)}")

Data type of element '1': <class 'str'>
Data type of element '2': <class 'str'>
Data type of element '3': <class 'str'>
Data type of element '4': <class 'str'>
Data type of element '5': <class 'str'>
Data type of element '1': <class 'numpy.int64'>
Data type of element '2': <class 'numpy.int64'>
Data type of element '3': <class 'numpy.int64'>
Data type of element '4': <class 'numpy.int64'>
Data type of element '5': <class 'numpy.int64'>


In [10]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Que4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

Ans:

In [21]:
# (i) Finding the shape of the array
shape = num_array.shape

# (ii) Finding the size of the array
size = num_array.size

print("Shape:", shape)
print("Size:", size)

Shape: (2, 3)
Size: 6


Que5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

Ans:

In [22]:
import numpy as np

zeros_matrix = np.zeros((3, 3))
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
zeros_matrix.shape

(3, 3)

In [20]:
zeros_matrix.size

9

Que6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Ans:

In [31]:
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
